### ISSUE TITLE
walk function is empty

### ISSUE THREAD

**Issue by 4x4falcon** [Gipsonek/ArduPod#2]
The walk function is empty.  So does not do what the readme says.

**Comment by jgromes** [comment]
Walk function is still work in progress, I forgot to put that in the readme.

**Comment by 4x4falcon** [comment]
Thanks.  Do you have any beta code for it.

**Comment by jgromes** [comment]
Sorry, I don't have any code for this function yet. For now, you have to use the step function in order to move the robot. Since I'm currently pretty busy with ArduRover, so I don't have any estimate when will I be able to return back to this. It might be faster for you to implement the walk function for yourself, if you really want to :)

**Comment by 4x4falcon** [comment]
Ok, thanks.  I'll see what I can come up with.
